<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	"Add to cart" => array(
		__( "Add to cart", 'wonder-cart' ),
	),
	"Checked by default" => array(
		__( "Checked by default", 'wonder-cart' ),
	),
	"Promotion options" => array(
		__( "Promotion options", 'wonder-cart' ),
	),
	"Back" => array(
		__( "Back", 'wonder-cart' ),
	),
	"Next" => array(
		__( "Next", 'wonder-cart' ),
	),
	"Finish" => array(
		__( "Finish", 'wonder-cart' ),
	),
	"Save Changes" => array(
		__( "Save Changes", 'wonder-cart' ),
	),
	"Are you sure?" => array(
		__( "Are you sure?", 'wonder-cart' ),
	),
	"Yes, proceed without saving" => array(
		__( "Yes, proceed without saving", 'wonder-cart' ),
	),
	"Do you want to come back to the dashboard? The changes made may not be saved." => array(
		__( "Do you want to come back to the dashboard? The changes made may not be saved.", 'wonder-cart' ),
	),
	"Back to WP" => array(
		__( "Back to WP", 'wonder-cart' ),
	),
	"Campaign created. Enjoy!" => array(
		__( "Campaign created. Enjoy!", 'wonder-cart' ),
	),
	"Are you sure you want to activate all campaigns?" => array(
		__( "Are you sure you want to activate all campaigns?", 'wonder-cart' ),
	),
	"Are you sure you want to deactivate all campaigns?" => array(
		__( "Are you sure you want to deactivate all campaigns?", 'wonder-cart' ),
	),
	"Are you sure you want to delete all campaigns?" => array(
		__( "Are you sure you want to delete all campaigns?", 'wonder-cart' ),
	),
	"Confirm action" => array(
		__( "Confirm action", 'wonder-cart' ),
	),
	"Yes" => array(
		__( "Yes", 'wonder-cart' ),
	),
	"This action cannot be undone and you will not be able to recover this data." => array(
		__( "This action cannot be undone and you will not be able to recover this data.", 'wonder-cart' ),
	),
	"Filter by type" => array(
		__( "Filter by type", 'wonder-cart' ),
	),
	"All type" => array(
		__( "All type", 'wonder-cart' ),
	),
	"Filter by status" => array(
		__( "Filter by status", 'wonder-cart' ),
	),
	"All status" => array(
		__( "All status", 'wonder-cart' ),
	),
	"Bulk actions" => array(
		__( "Bulk actions", 'wonder-cart' ),
	),
	"Select action" => array(
		__( "Select action", 'wonder-cart' ),
	),
	"Apply" => array(
		__( "Apply", 'wonder-cart' ),
	),
	"List view" => array(
		__( "List view", 'wonder-cart' ),
	),
	"Edit" => array(
		__( "Edit", 'wonder-cart' ),
	),
	"Duplicate" => array(
		__( "Duplicate", 'wonder-cart' ),
	),
	"Delete" => array(
		__( "Delete", 'wonder-cart' ),
	),
	"Scheduled (%s)" => array(
		__( "Scheduled (%s)", 'wonder-cart' ),
	),
	"No start date" => array(
		__( "No start date", 'wonder-cart' ),
	),
	"Type:" => array(
		__( "Type:", 'wonder-cart' ),
	),
	"Status:" => array(
		__( "Status:", 'wonder-cart' ),
	),
	"End on:" => array(
		__( "End on:", 'wonder-cart' ),
	),
	"No end date" => array(
		__( "No end date", 'wonder-cart' ),
	),
	"Confirm delete" => array(
		__( "Confirm delete", 'wonder-cart' ),
	),
	"Yes, delete" => array(
		__( "Yes, delete", 'wonder-cart' ),
	),
	"Enable campaign" => array(
		__( "Enable campaign", 'wonder-cart' ),
	),
	"Campaign deleted" => array(
		__( "Campaign deleted", 'wonder-cart' ),
	),
	"No campaigns found" => array(
		__( "No campaigns found", 'wonder-cart' ),
	),
	"Try changing the filter view or" => array(
		__( "Try changing the filter view or", 'wonder-cart' ),
	),
	"View all campaigns" => array(
		__( "View all campaigns", 'wonder-cart' ),
	),
	"Show more" => array(
		__( "Show more", 'wonder-cart' ),
	),
	"Cancel" => array(
		__( "Cancel", 'wonder-cart' ),
	),
	"Create and manage X-sell, Upsell, sales and promotions through campaigns to boost your sales." => array(
		__( "Create and manage X-sell, Upsell, sales and promotions through campaigns to boost your sales.", 'wonder-cart' ),
	),
	"Sales & Promotions" => array(
		__( "Sales & Promotions", 'wonder-cart' ),
	),
	"All Campaigns" => array(
		__( "All Campaigns", 'wonder-cart' ),
	),
	"Settings" => array(
		__( "Settings", 'wonder-cart' ),
	),
	"Reports" => array(
		__( "Reports", 'wonder-cart' ),
	),
	"Search" => array(
		__( "Search", 'wonder-cart' ),
	),
	"Trigger when any of these conditions are met:" => array(
		__( "Trigger when any of these conditions are met:", 'wonder-cart' ),
	),
	"Trigger when all of these conditions are met:" => array(
		__( "Trigger when all of these conditions are met:", 'wonder-cart' ),
	),
	"Condition #%s" => array(
		__( "Condition #%s", 'wonder-cart' ),
	),
	"Set conditions before continuing" => array(
		__( "Set conditions before continuing", 'wonder-cart' ),
	),
	"Cart discount conditions" => array(
		__( "Cart discount conditions", 'wonder-cart' ),
	),
	"Cart discount will be applied only when the following conditions are met." => array(
		__( "Cart discount will be applied only when the following conditions are met.", 'wonder-cart' ),
	),
	"Offer discount at cart only when" => array(
		__( "Offer discount at cart only when", 'wonder-cart' ),
	),
	"Save" => array(
		__( "Save", 'wonder-cart' ),
	),
	"on" => array(
		__( "on", 'wonder-cart' ),
	),
	"% - percentage" => array(
		__( "% - percentage", 'wonder-cart' ),
	),
	"%s - fixed" => array(
		__( "%s - fixed", 'wonder-cart' ),
	),
	"Discount for" => array(
		__( "Discount for", 'wonder-cart' ),
	),
	"Set discount rules before continuing" => array(
		__( "Set discount rules before continuing", 'wonder-cart' ),
	),
	"Discount for categories rules" => array(
		__( "Discount for categories rules", 'wonder-cart' ),
	),
	"Set the discount to apply to all products of selected categories." => array(
		__( "Set the discount to apply to all products of selected categories.", 'wonder-cart' ),
	),
	"Time" => array(
		__( "Time", 'wonder-cart' ),
	),
	"...other %s" => array(
		_n( "...other %s", "...others %s", 1, 'wonder-cart' ),
		_n( "...other %s", "...others %s", 2, 'wonder-cart' ),
	),
	"Search for countries" => array(
		__( "Search for countries", 'wonder-cart' ),
	),
	"Search for states or provinces" => array(
		__( "Search for states or provinces", 'wonder-cart' ),
	),
	"Free Shipping conditions" => array(
		__( "Free Shipping conditions", 'wonder-cart' ),
	),
	"Free Shipping will be applied only when the following conditions are met." => array(
		__( "Free Shipping will be applied only when the following conditions are met.", 'wonder-cart' ),
	),
	"Offer free shipping only when" => array(
		__( "Offer free shipping only when", 'wonder-cart' ),
	),
	"Search for products" => array(
		__( "Search for products", 'wonder-cart' ),
	),
	"Search for product categories" => array(
		__( "Search for product categories", 'wonder-cart' ),
	),
	"Gift product at cart conditions" => array(
		__( "Gift product at cart conditions", 'wonder-cart' ),
	),
	"Products will be offered as gifts in cart only when the following conditions are met." => array(
		__( "Products will be offered as gifts in cart only when the following conditions are met.", 'wonder-cart' ),
	),
	"Offer gift product only when" => array(
		__( "Offer gift product only when", 'wonder-cart' ),
	),
	"No file provided." => array(
		__( "No file provided.", 'wonder-cart' ),
	),
	"Sorry, you are not allowed to upload %s files." => array(
		__( "Sorry, you are not allowed to upload %s files.", 'wonder-cart' ),
	),
	"You cannot drop files here." => array(
		__( "You cannot drop files here.", 'wonder-cart' ),
	),
	"Upload file" => array(
		__( "Upload file", 'wonder-cart' ),
	),
	"Enter url" => array(
		__( "Enter url", 'wonder-cart' ),
	),
	"Check to set as default" => array(
		__( "Check to set as default", 'wonder-cart' ),
	),
	"units = " => array(
		__( "units = ", 'wonder-cart' ),
	),
	"Discount for quantity rules" => array(
		__( "Discount for quantity rules", 'wonder-cart' ),
	),
	"Set the discount for quantity rules for the selected products." => array(
		__( "Set the discount for quantity rules for the selected products.", 'wonder-cart' ),
	),
	"units" => array(
		__( "units", 'wonder-cart' ),
	),
	"unit" => array(
		__( "unit", 'wonder-cart' ),
	),
	"discount" => array(
		__( "discount", 'wonder-cart' ),
	),
	"Please enter a link here " => array(
		__( "Please enter a link here ", 'wonder-cart' ),
	),
	"Press ENTER to add this link" => array(
		__( "Press ENTER to add this link", 'wonder-cart' ),
	),
	"Searching for url.." => array(
		__( "Searching for url..", 'wonder-cart' ),
	),
	"Search or type url" => array(
		__( "Search or type url", 'wonder-cart' ),
	),
	"Please, select at least one product " => array(
		__( "Please, select at least one product ", 'wonder-cart' ),
	),
	"Please, select at least one category" => array(
		__( "Please, select at least one category", 'wonder-cart' ),
	),
	"No results" => array(
		__( "No results", 'wonder-cart' ),
	),
	"No results found for %s" => array(
		__( "No results found for %s", 'wonder-cart' ),
	),
	"Please enter a text here " => array(
		__( "Please enter a text here ", 'wonder-cart' ),
	),
	"% - percentage discount" => array(
		__( "% - percentage discount", 'wonder-cart' ),
	),
	"%s - fixed discount" => array(
		__( "%s - fixed discount", 'wonder-cart' ),
	),
	"%d %s = %d %s with %s discount" => array(
		__( "%d %s = %d %s with %s discount", 'wonder-cart' ),
	),
	"Promo rule" => array(
		__( "Promo rule", 'wonder-cart' ),
	),
	"Set the discount to apply to products of selected categories." => array(
		__( "Set the discount to apply to products of selected categories.", 'wonder-cart' ),
	),
	"If users purchases" => array(
		__( "If users purchases", 'wonder-cart' ),
	),
	"item of" => array(
		_n( "item of", "items of", 1, 'wonder-cart' ),
		_n( "item of", "items of", 2, 'wonder-cart' ),
	),
	"gets" => array(
		__( "gets", 'wonder-cart' ),
	),
	"of " => array(
		__( "of ", 'wonder-cart' ),
	),
	"with a " => array(
		__( "with a ", 'wonder-cart' ),
	),
	"NOW" => array(
		__( "NOW", 'wonder-cart' ),
	),
	"Now you can activate it with just one click or schedule it using the calendar below." => array(
		__( "Now you can activate it with just one click or schedule it using the calendar below.", 'wonder-cart' ),
	),
	"Promo starts:" => array(
		__( "Promo starts:", 'wonder-cart' ),
	),
	"Set the end date" => array(
		__( "Set the end date", 'wonder-cart' ),
	),
	"Promo ends:" => array(
		__( "Promo ends:", 'wonder-cart' ),
	),
	"Schedule Campaign" => array(
		__( "Schedule Campaign", 'wonder-cart' ),
	),
	"Start Campaign Now" => array(
		__( "Start Campaign Now", 'wonder-cart' ),
	),
	"Create now" => array(
		__( "Create now", 'wonder-cart' ),
	),
	"Create a new campaign" => array(
		__( "Create a new campaign", 'wonder-cart' ),
	),
	"Options saved" => array(
		__( "Options saved", 'wonder-cart' ),
	),
	"Options reset!" => array(
		__( "Options reset!", 'wonder-cart' ),
	),
	"Discard Changes" => array(
		__( "Discard Changes", 'wonder-cart' ),
	),
	"Yes, reset" => array(
		__( "Yes, reset", 'wonder-cart' ),
	),
	"Do you want reset to default value all options in this page?" => array(
		__( "Do you want reset to default value all options in this page?", 'wonder-cart' ),
	),
	"Preview" => array(
		__( "Preview", 'wonder-cart' ),
	),
	"Time is up!" => array(
		__( "Time is up!", 'wonder-cart' ),
	),
	"Free!" => array(
		__( "Free!", 'wonder-cart' ),
	),
	"Cart subtotal" => array(
		__( "Cart subtotal", 'wonder-cart' ),
	),
	"Discount" => array(
		__( "Discount", 'wonder-cart' ),
	),
	"Cart total" => array(
		__( "Cart total", 'wonder-cart' ),
	),
	"Category Page" => array(
		__( "Category Page", 'wonder-cart' ),
	),
	"Shipping" => array(
		__( "Shipping", 'wonder-cart' ),
	),
	"FREE" => array(
		__( "FREE", 'wonder-cart' ),
	),
	"The offer ends in:" => array(
		__( "The offer ends in:", 'wonder-cart' ),
	),
	"Report" => array(
		__( "Report", 'wonder-cart' ),
	),
	"Coming Soon" => array(
		__( "Coming Soon", 'wonder-cart' ),
	),
	"We're working hard to complete the development of this section. " => array(
		__( "We're working hard to complete the development of this section. ", 'wonder-cart' ),
	),
	"Campaign status" => array(
		__( "Campaign status", 'wonder-cart' ),
	),
	"Start date:" => array(
		__( "Start date:", 'wonder-cart' ),
	),
	"Set the end date:" => array(
		__( "Set the end date:", 'wonder-cart' ),
	),
	"Campaign updated!" => array(
		__( "Campaign updated!", 'wonder-cart' ),
	),
	"Continue to edit the campaign or exit the edit mode to go back to the dashboard" => array(
		__( "Continue to edit the campaign or exit the edit mode to go back to the dashboard", 'wonder-cart' ),
	),
	"Exit edit mode" => array(
		__( "Exit edit mode", 'wonder-cart' ),
	),
	"Everything you need to boost your sales." => array(
		__( "Everything you need to boost your sales.", 'wonder-cart' ),
	),
	"Create and manage deals, sales promotions and upsell campaigns in your shop" => array(
		__( "Create and manage deals, sales promotions and upsell campaigns in your shop", 'wonder-cart' ),
	),
	"Create campaign" => array(
		__( "Create campaign", 'wonder-cart' ),
	),
	"You haven't created any campaigns yet." => array(
		__( "You haven't created any campaigns yet.", 'wonder-cart' ),
	),
	"Create your first one now to boost your sales!" => array(
		__( "Create your first one now to boost your sales!", 'wonder-cart' ),
	),
	"Global Style" => array(
		__( "Global Style", 'wonder-cart' ),
	),
	"Campaigns" => array(
		__( "Campaigns", 'wonder-cart' ),
	),
	"General" => array(
		__( "General", 'wonder-cart' ),
	),
	"Active" => array(
		__( "Active", 'wonder-cart' ),
	),
	"Inactive" => array(
		__( "Inactive", 'wonder-cart' ),
	),
	"Scheduled" => array(
		__( "Scheduled", 'wonder-cart' ),
	),
	"Ended" => array(
		__( "Ended", 'wonder-cart' ),
	),
	"Activate all" => array(
		__( "Activate all", 'wonder-cart' ),
	),
	"Deactivate all" => array(
		__( "Deactivate all", 'wonder-cart' ),
	),
	"Delete all" => array(
		__( "Delete all", 'wonder-cart' ),
	),
	"Documentation" => array(
		__( "Documentation", 'wonder-cart' ),
	),
	"Get Help" => array(
		__( "Get Help", 'wonder-cart' ),
	),
	"Always, without any conditions set" => array(
		__( "Always, without any conditions set", 'wonder-cart' ),
	),
	"Only when specific conditions are met" => array(
		__( "Only when specific conditions are met", 'wonder-cart' ),
	),
	"any" => array(
		__( "any", 'wonder-cart' ),
	),
	"all" => array(
		__( "all", 'wonder-cart' ),
	),
	"Cart total amount" => array(
		__( "Cart total amount", 'wonder-cart' ),
	),
	"Number of orders" => array(
		__( "Number of orders", 'wonder-cart' ),
	),
	"Total amount spent" => array(
		__( "Total amount spent", 'wonder-cart' ),
	),
	"Has specific products in cart" => array(
		__( "Has specific products in cart", 'wonder-cart' ),
	),
	"Has specific product categories in cart" => array(
		__( "Has specific product categories in cart", 'wonder-cart' ),
	),
	"State/Province is" => array(
		__( "State/Province is", 'wonder-cart' ),
	),
	"State/Province is not" => array(
		__( "State/Province is not", 'wonder-cart' ),
	),
	"Country is" => array(
		__( "Country is", 'wonder-cart' ),
	),
	"Country is not" => array(
		__( "Country is not", 'wonder-cart' ),
	),
	"at least one of this products" => array(
		__( "at least one of this products", 'wonder-cart' ),
	),
	"all selected products" => array(
		__( "all selected products", 'wonder-cart' ),
	),
	"at least one of this product categories" => array(
		__( "at least one of this product categories", 'wonder-cart' ),
	),
	"all selected product categories" => array(
		__( "all selected product categories", 'wonder-cart' ),
	),
	"is at least" => array(
		__( "is at least", 'wonder-cart' ),
	),
	"is to the utmost" => array(
		__( "is to the utmost", 'wonder-cart' ),
	),
	"is exactly" => array(
		__( "is exactly", 'wonder-cart' ),
	),
	"Total:" => array(
		__( "Total:", 'wonder-cart' ),
	),
	"You've chosen all your gifts!" => array(
		__( "You've chosen all your gifts!", 'wonder-cart' ),
	),
	"To pick a different one  remove a gift from your list" => array(
		__( "To pick a different one  remove a gift from your list", 'wonder-cart' ),
	),
	"No, thanks" => array(
		__( "No, thanks", 'wonder-cart' ),
	),
	"View cart & checkout" => array(
		__( "View cart & checkout", 'wonder-cart' ),
	),
	"Keep Shopping" => array(
		__( "Keep Shopping", 'wonder-cart' ),
	),
	"Select options" => array(
		__( "Select options", 'wonder-cart' ),
	),
	"Save %s" => array(
		__( "Save %s", 'wonder-cart' ),
	),
	"Please set the options of missing quantities before to add to cart" => array(
		__( "Please set the options of missing quantities before to add to cart", 'wonder-cart' ),
	),
	"/unit" => array(
		__( "/unit", 'wonder-cart' ),
	),
	"quantity" => array(
		_n( "quantity", "quantities", 1, 'wonder-cart' ),
		_n( "quantity", "quantities", 2, 'wonder-cart' ),
	),
	"+ Set quantity for variations" => array(
		__( "+ Set quantity for variations", 'wonder-cart' ),
	),
	"Thank you!" => array(
		__( "Thank you!", 'wonder-cart' ),
	),
	"Products added to your cart" => array(
		__( "Products added to your cart", 'wonder-cart' ),
	),
	"Choose option" => array(
		__( "Choose option", 'wonder-cart' ),
	),
	"No products found." => array(
		__( "No products found.", 'wonder-cart' ),
	),
	"[PART OF] Offer discount at cart only when all/any of these conditions are met:of these conditions are met:" => array(
		_x( "of these conditions are met:", "[PART OF] Offer discount at cart only when all/any of these conditions are met:", 'wonder-cart' ),
	),
	"Tooltip in the \" Dimensions\" fieldLinked" => array(
		_x( "Linked", "Tooltip in the \" Dimensions\" field", 'wonder-cart' ),
	),
	"Tooltip in the \" Dimensions\" fieldUnlinked" => array(
		_x( "Unlinked", "Tooltip in the \" Dimensions\" field", 'wonder-cart' ),
	),
	"Position in the \"Dimensions\" fieldTop" => array(
		_x( "Top", "Position in the \"Dimensions\" field", 'wonder-cart' ),
	),
	"Position in the \"Dimensions\" fieldRight" => array(
		_x( "Right", "Position in the \"Dimensions\" field", 'wonder-cart' ),
	),
	"Position in the \"Dimensions\" fieldBottom" => array(
		_x( "Bottom", "Position in the \"Dimensions\" field", 'wonder-cart' ),
	),
	"Position in the \"Dimensions\" fieldLeft" => array(
		_x( "Left", "Position in the \"Dimensions\" field", 'wonder-cart' ),
	),
	"[PART OF] : Drag or Upload a fileDrag or " => array(
		_x( "Drag or ", "[PART OF] : Drag or Upload a file", 'wonder-cart' ),
	),
	"[PART OF] : Drag or Upload a fileUpload file" => array(
		_x( "Upload file", "[PART OF] : Drag or Upload a file", 'wonder-cart' ),
	),
	"[Part OF]: Shop category%s category" => array(
		_x( "%s category", "[Part OF]: Shop category", 'wonder-cart' ),
	),
	"[PART OF STRING:Well done!You just created a successful promo!]Well done!" => array(
		_x( "Well done!", "[PART OF STRING:Well done!You just created a successful promo!]", 'wonder-cart' ),
	),
	"[PART OF STRING:Well done!You just created a successful promo!]You just created a successful promo!" => array(
		_x( "You just created a successful promo!", "[PART OF STRING:Well done!You just created a successful promo!]", 'wonder-cart' ),
	),
);