<?php

/**
 * An array of flat rate boxes sizes for USPS
 */
return array(
	'USPS'  => array(
		'FlatRateEnvelope'            => array(
			'name'   => 'Letter Envelope',
			'length' => '12.5',
			'width'  => '9.5',
			'height' => '1',
			'weight' => '70',
			'type'   => 'envelope',
		),
		'FlatRateGiftCardEnvelope'    => array(
			'name'   => 'Gift Card Envelopes',
			'length' => '10',
			'width'  => '7',
			'height' => '0.25',
			'weight' => '70',
			'type'   => 'envelope',
		),
		'FlatRateWindowEnvelope'      => array(
			'name'   => 'Window Envelopes',
			'length' => '10',
			'width'  => '5',
			'height' => '0.25',
			'weight' => '70',
			'type'   => 'envelope',
		),
		'SmallFlatRateEnvelope'       => array(
			'name'   => 'Small Envelopes',
			'length' => '10',
			'width'  => '6',
			'height' => '0.25',
			'weight' => '70',
			'type'   => 'envelope',
		),
		'FlatRatePaddedEnvelope'      => array(
			'name'   => 'Padded Envelopes',
			'length' => '12.5',
			'width'  => '9.5',
			'height' => '1',
			'weight' => '70',
			'type'   => 'envelope',
		),
		'FlatRateLegalEnvelope'       => array(
			'name'   => 'Legal Envelopes',
			'length' => '15',
			'width'  => '9.5',
			'height' => '0.25',
			'weight' => '70',
			'type'   => 'envelope',
		),
		'SmallFlatRateBox'            => array(
			'name'   => 'Small Box',
			'length' => '8.6875',
			'width'  => '5.4375',
			'height' => '1.75',
			'weight' => '70',
		),
		'MediumFlatRateBox'           => array(
			'name'   => 'Medium Box - 1',
			'length' => '11.25',
			'width'  => '8.75',
			'height' => '6',
			'weight' => '70',
		),
		'MediumFlatRateBox-2'         => array(
			'name'   => 'Medium Box - 2',
			'length' => '14',
			'width'  => '12',
			'height' => '3.5',
			'weight' => '70',
		),
		'LargeFlatRateBox'            => array(
			'name'   => 'Large Box - 1',
			'length' => '12.25',
			'width'  => '12.25',
			'height' => '6',
			'weight' => '70',
		),
		'LargeFlatRateBox-2'          => array(
			'name'   => 'Large Box - 2',
			'length' => '24.0625',
			'width'  => '11.875',
			'height' => '3.125',
			'weight' => '70',
		),
		'FlatRateCardboardEnvelope'   => array(
			'name'   => 'Cardboard Envelope',
			'length' => '12.5',
			'width'  => '9.5',
			'height' => '1',
			'weight' => '70',
		),
		'RegionalRateBoxA'            => array(
			'name'   => 'Regional Rate Box A - 1',
			'length' => '10.125',
			'width'  => '7.125',
			'height' => '5',
			'weight' => '15',
		),
		'RegionalRateBoxA-2'          => array(
			'name'   => 'Regional Rate Box A - 2',
			'length' => '16.166',
			'width'  => '11.166',
			'height' => '2.5',
			'weight' => '15',
		),
		'RegionalRateBoxB'            => array(
			'name'   => 'Regional Rate Box B - 1',
			'length' => '12.25',
			'width'  => '10.5',
			'height' => '5.5',
			'weight' => '20',
		),
		'RegionalRateBoxB-2'          => array(
			'name'   => 'Regional Rate Box B - 2',
			'length' => '16.25',
			'width'  => '14.5',
			'height' => '3',
			'weight' => '20',
		),
		'LargeFlatRateBoardGameBox'   => array(
			'name'   => 'LF Board Game Box - 1',
			'length' => '23.687',
			'width'  => '11.75',
			'height' => '3',
			'weight' => '70',
		),
		'LargeFlatRateBoardGameBox-2' => array(
			'name'   => 'LF Board Game Box - 2',
			'length' => '24.062',
			'width'  => '11.875',
			'height' => '3.125',
			'weight' => '70',
		),
		'Card'                        => array(
			'name'   => 'Card',
			'length' => '4.25',
			'width'  => '6',
			'height' => '1',
			'weight' => '0',
		),
		'Letter'                      => array(
			'name'   => 'Letter',
			'length' => '6.125',
			'width'  => '11.05',
			'height' => '1',
			'weight' => '0.21875',
		),
		'Flat'                        => array(
			'name'   => 'Flat',
			'length' => '12',
			'width'  => '15',
			'height' => '1',
			'weight' => '0.8125',
		),
	),
	'FedEx' => array(
		'FedExEnvelope'        => array(
			'name'   => 'FedEx Envelope',
			'length' => '9.5',
			'width'  => '12.5',
			'height' => '1',
			'weight' => '0.5',
		),
		'FedExSmallBox'        => array(
			'name'   => 'FedEx SmallBox - 1',
			'length' => '12.25',
			'width'  => '10.5',
			'height' => '1.5',
			'weight' => '20',
		),
		'FedExSmallBox-2'      => array(
			'name'   => 'FedEx SmallBox - 2',
			'length' => '8.75',
			'width'  => '2.63',
			'height' => '11.25',
			'weight' => '20',
		),
		'FedExMediumBox'       => array(
			'name'   => 'FedEx Medium Box - 1',
			'length' => '13.25',
			'width'  => '11.5',
			'height' => '2.38',
			'weight' => '20',
		),
		'FedExMediumBox-2'     => array(
			'name'   => 'FedEx Medium Box - 2',
			'length' => '8.75',
			'width'  => '4.38',
			'height' => '11.25',
			'weight' => '20',
		),
		'FedExLargeBox'        => array(
			'name'   => 'FedEx Large Box - 1',
			'length' => '17.88',
			'width'  => '12.38',
			'height' => '3',
			'weight' => '20',
		),
		'FedExLargeBox-2'      => array(
			'name'   => 'FedEx Large Box - 2',
			'length' => '8.75',
			'width'  => '7.75',
			'height' => '11.25',
			'weight' => '20',
		),
		'FedExExtraLargeBox'   => array(
			'name'   => 'FedEx Extra Large Box - 1',
			'length' => '11.88',
			'width'  => '10.75',
			'height' => '11',
			'weight' => '20',
		),
		'FedExExtraLargeBox-2' => array(
			'name'   => 'FedEx Extra Large Box - 2',
			'length' => '15.25',
			'width'  => '14.13',
			'height' => '6',
			'weight' => '20',
		),
		'FedExPak'             => array(
			'name'   => 'FedEx Pak',
			'length' => '12',
			'width'  => '15.5',
			'height' => '1',
			'weight' => '5.5',
		),
		'FedEx10kgBox'         => array(
			'name'   => 'FedEx 10kg Box',
			'length' => '15.81',
			'width'  => '12.94',
			'height' => '10.19',
			'weight' => '22',
		),
		'FedEx25kgBox'         => array(
			'name'   => 'FedEx 25kg Box',
			'length' => '21.56',
			'width'  => '16.56',
			'height' => '13.19',
			'weight' => '55',
		),

	),
);
